/*
 * This source file was generated by the Gradle 'init' task
 */
package org.flate;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	public String hello() {
		return "Hello World";
	}

    @Test void appHasAGreeting() {
        Flate classUnderTest = new Flate();
		hello();
    }
}
